version: 0.2

env:
  variables:
    APP_ARTIFACT_NAME: stocktrading-flink-artifact
    FLINK_SRC: https://github.com/apache/flink/archive
    FLINK_CONNECTOR: flink-connector-kinesis
    FLINK_VERSION: 1.6.2
    KINESIS_VERSION: 2.11
    ROLE: "SandboxCodeBuildAssume"
    ACCOUNT: "123456789012"
    NAME: "SessionCodeBuildSandboxDeploy"

phases:
  install:
    runtime-versions:
      java: openjdk8

  pre_build:
    commands:
      - curl -L https://github.com/apache/flink/archive/release-${FLINK_VERSION}.zip -o "release-${FLINK_VERSION}.zip"
      - unzip release-${FLINK_VERSION}.zip
      - cd flink-release-$FLINK_VERSION
      - mvn clean install -B -DskipTests -Dfast -Pinclude-kinesis -pl flink-connectors/flink-connector-kinesis
      - cd ..

  build:
    commands:
      - mvn package -DskipTests -Djar.finalName=stockrading-analytics-$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "CodeBuild Source Location - " $CODEBUILD_SRC_DIR
      - cat /etc/*release*
      - aws ssm put-parameter --name "flink-app-filename" --type "String" --value "stocktrading-analytics-${CODEBUILD_RESOLVED_SOURCE_VERSION}.jar" --overwrite

artifacts:
  files:
    - stocktrading-analytics-${CODEBUILD_RESOLVED_SOURCE_VERSION}.jar
  name: $APP_ARTIFACT_NAME
  base-directory: target

cache:
  paths:
    - '/root/.m2/**/*'